import { FruitsView } from '@/components/fruits/FruitsView';

// Prerender params for SSG
export function generateStaticParams() {
    return [
        { locale: 'en' },
        { locale: 'et' }
    ];
}

export const metadata = {
    title: 'Fruits (Applications) - AI Tree',
    description: 'Explore the applications and value generated by AI.'
};

export default function FruitsPage({ params }: { params: { locale: string } }) {
    return <FruitsView locale={params.locale} />;
}
