import { FruitsView } from '@/components/fruits/FruitsView';
import { getStageContent } from '@/actions/getConcepts';

// ISR: revalidate every 60s so new concepts appear quickly
export const revalidate = 60;

export function generateStaticParams() {
    return [
        { locale: 'en' },
        { locale: 'et' }
    ];
}

export const metadata = {
    title: 'Fruits (Applications) - AI Tree',
    description: 'Explore the applications and value generated by AI.'
};

export default async function FruitsPage({ params }: { params: Promise<{ locale: string }> }) {
    const { locale } = await params;
    const concepts = await getStageContent('fruits', locale);
    return <FruitsView concepts={concepts} locale={locale} />;
}
