import { FruitsView } from '@/components/fruits/FruitsView';
import { getStageContent } from '@/actions/getConcepts';
import { getRelatedConceptsForStage } from '@/lib/concepts/api';

// ISR: revalidate every 60s so new concepts appear quickly
export const revalidate = 60;

export function generateStaticParams() {
    return [
        { locale: 'en' },
        { locale: 'et' }
    ];
}

export const metadata = {
    title: 'Fruits (Applications) - AI Tree',
    description: 'Explore the applications and value generated by AI.'
};

export default async function FruitsPage({ params }: { params: Promise<{ locale: string }> }) {
    const { locale } = await params;
    const [concepts, relatedConcepts] = await Promise.all([
        getStageContent('fruits', locale),
        getRelatedConceptsForStage('fruits', locale, 6),
    ]);
    return <FruitsView concepts={concepts} relatedConcepts={relatedConcepts} locale={locale} />;
}
